drom:
    resource: "@DromBundle/Controller/"
    type:     annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

fos_user_registration_confirm:
    path:      /confirm/{token}
    defaults:  { _controller: FOSUserBundle:Registration:confirm }

app:
    resource: '@AppBundle/Controller/'
    type:     annotation

rest_app:
    resource: "@AppBundle/Resources/config/routing.yml"